FIND_PATH(uv_INCLUDE_DIR NAMES uv.h HINTS /usr/local/include)
FIND_LIBRARY(uv_LIBRARIES NAMES uv libuv HINTS /usr/local/lib)

set(_FL_OLD "${CMAKE_FIND_LIBRARY_SUFFIXES}")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
FIND_LIBRARY(uv_LIBRARIES_STATIC NAMES uv libuv HINTS /usr/local/lib)
set(CMAKE_FIND_LIBRARY_SUFFIXES "${_FL_OLD}")
unset(_FL_OLD)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(uv DEFAULT_MSG uv_LIBRARIES uv_INCLUDE_DIR)
